language: elixir

matrix:
  include:
    - otp_release: 18.3
      elixir: 1.2.6
    - otp_release: 18.3
      elixir: 1.3.1
    - otp_release: 19.0
      elixir: 1.3.1

sudo: false
notifications:
  recipients:
    - self@falood.me
before_script:
  - mix deps.get --only test
after_script:
  - MIX_ENV=docs mix deps.get
  - MIX_ENV=docs mix inch.report
